openapi: 3.0.3
info:
  title: Customer API
  version: 1.0.0

paths:
  /customers:
    post:
      summary: Create customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerRequest'
      responses:
        '201':
          description: Customer created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerResponse'

components:
  schemas:
    CustomerRequest:
      type: object
      required: [name, email]
      properties:
        name:
          type: string
        email:
          type: string

    CustomerResponse:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
