spring:
  data:
    mongodb:
      #uri: mongodb://localhost:27017/bank
      uri: mongodb://admin:admin123@localhost:27017/bootcampbd?authSource=admin

logging:
  level:
    org.mongodb.driver: DEBUG
