spring:
  application:
    name: customer-service

  data:
    mongodb:
      uri: mongodb://admin:admin123@mongodb:27017/customerdb?authSource=admin

  cloud:
    config:
      # Evita que el servicio muera si el config-server
      # tarda unos segundos en estar disponible
      fail-fast: false

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always
