server:
  port: 8761

spring:
  application:
    name: discovery

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: discovery

management:
  endpoints:
    web:
      exposure:
        include: health,info
